### ISSUE TITLE
Join rosetta-rs?

### ISSUE THREAD

**Issue by epage** [xacrimon/conc-map-bench#7]
I've been maintaining several benchmark repos based off of [`template-benchmarks-rs`](https://github.com/djc/template-benchmarks-rs).  I've noticed there are [several other benchmark repos](https://www.reddit.com/r/rust/comments/w24rmg/github_epageparsebenchmarksrs/ignzypd/) that are hard to know about.

I've created rosetta-rs org as a place for these repos if the authors so choose to
- Increase discoverability
- Improve bus factor

See the [meta repo](https://github.com/rosetta-rs/team) for more details

Interested in collaborating?

**Comment by xacrimon** [comment]
Not interested at the moment
